name: Dart CI

on: [push]

jobs:
  teset:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.14'
          channel: 'dev'
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter pub run test
