name: Dart CI

on: [push]

jobs:
  teset:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.13.x'
          channel: 'beta'

      - run: flutter pub get
      - run: flutter test
